title: kappa
logo: /assets/img/logo.jpg
description: Cybersecurity enthusiast :)
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
